### PR TITLE
WASI: use getentropy to get randomized bytes

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Resolve https://github.com/swiftwasm/swift/issues/3320

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
Submitted upstream as https://github.com/apple/swift-corelibs-foundation/pull/3025

**Comment by kateinoigakukun** [comment]
This should be cherry-picked to swiftwasm and 5.5 branch also

**Comment by kateinoigakukun** [comment]
I confirmed this patch correctly fixed the issue
```
$ cat main.swift
import Foundation

print(UUID())

$ wasmer ./main
C46125EF-A0D1-4440-80B0-83FD50275AFD

$ wasmer ./main
5A96D625-EA41-42ED-AC20-EDA178E1D474
```

**Comment by MaxDesiatov** [comment]
SwiftWasm 5.5 PR is merged, it will land on `swiftwasm` when https://github.com/apple/swift-corelibs-foundation/pull/3025 is merged upstream.

**Pull request merged**
